//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TelefonijaKLijent.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceOperater")]
    public interface IServiceOperater {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/dodajMinute", ReplyAction="http://tempuri.org/IServiceOperater/dodajMinuteResponse")]
        void dodajMinute(string racun, int minuti, float tarifa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/dodajMinute", ReplyAction="http://tempuri.org/IServiceOperater/dodajMinuteResponse")]
        System.Threading.Tasks.Task dodajMinuteAsync(string racun, int minuti, float tarifa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/dodajPoruke", ReplyAction="http://tempuri.org/IServiceOperater/dodajPorukeResponse")]
        void dodajPoruke(string racun, int poruke, float tarifa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/dodajPoruke", ReplyAction="http://tempuri.org/IServiceOperater/dodajPorukeResponse")]
        System.Threading.Tasks.Task dodajPorukeAsync(string racun, int poruke, float tarifa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/dodajInternet", ReplyAction="http://tempuri.org/IServiceOperater/dodajInternetResponse")]
        void dodajInternet(string racun, int mb, float tarifa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/dodajInternet", ReplyAction="http://tempuri.org/IServiceOperater/dodajInternetResponse")]
        System.Threading.Tasks.Task dodajInternetAsync(string racun, int mb, float tarifa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiStanje", ReplyAction="http://tempuri.org/IServiceOperater/vratiStanjeResponse")]
        string vratiStanje(string racun);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/vratiStanje", ReplyAction="http://tempuri.org/IServiceOperater/vratiStanjeResponse")]
        System.Threading.Tasks.Task<string> vratiStanjeAsync(string racun);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/dodajRacun", ReplyAction="http://tempuri.org/IServiceOperater/dodajRacunResponse")]
        void dodajRacun(string brRacuna, int min, int poruke, int mb);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceOperater/dodajRacun", ReplyAction="http://tempuri.org/IServiceOperater/dodajRacunResponse")]
        System.Threading.Tasks.Task dodajRacunAsync(string brRacuna, int min, int poruke, int mb);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceOperaterChannel : TelefonijaKLijent.ServiceReference1.IServiceOperater, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceOperaterClient : System.ServiceModel.ClientBase<TelefonijaKLijent.ServiceReference1.IServiceOperater>, TelefonijaKLijent.ServiceReference1.IServiceOperater {
        
        public ServiceOperaterClient() {
        }
        
        public ServiceOperaterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceOperaterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOperaterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceOperaterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void dodajMinute(string racun, int minuti, float tarifa) {
            base.Channel.dodajMinute(racun, minuti, tarifa);
        }
        
        public System.Threading.Tasks.Task dodajMinuteAsync(string racun, int minuti, float tarifa) {
            return base.Channel.dodajMinuteAsync(racun, minuti, tarifa);
        }
        
        public void dodajPoruke(string racun, int poruke, float tarifa) {
            base.Channel.dodajPoruke(racun, poruke, tarifa);
        }
        
        public System.Threading.Tasks.Task dodajPorukeAsync(string racun, int poruke, float tarifa) {
            return base.Channel.dodajPorukeAsync(racun, poruke, tarifa);
        }
        
        public void dodajInternet(string racun, int mb, float tarifa) {
            base.Channel.dodajInternet(racun, mb, tarifa);
        }
        
        public System.Threading.Tasks.Task dodajInternetAsync(string racun, int mb, float tarifa) {
            return base.Channel.dodajInternetAsync(racun, mb, tarifa);
        }
        
        public string vratiStanje(string racun) {
            return base.Channel.vratiStanje(racun);
        }
        
        public System.Threading.Tasks.Task<string> vratiStanjeAsync(string racun) {
            return base.Channel.vratiStanjeAsync(racun);
        }
        
        public void dodajRacun(string brRacuna, int min, int poruke, int mb) {
            base.Channel.dodajRacun(brRacuna, min, poruke, mb);
        }
        
        public System.Threading.Tasks.Task dodajRacunAsync(string brRacuna, int min, int poruke, int mb) {
            return base.Channel.dodajRacunAsync(brRacuna, min, poruke, mb);
        }
    }
}
