//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EBankaInterface.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IServiceEBanka")]
    public interface IServiceEBanka {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEBanka/vratiStanje", ReplyAction="http://tempuri.org/IServiceEBanka/vratiStanjeResponse")]
        string vratiStanje(string brRacuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEBanka/vratiStanje", ReplyAction="http://tempuri.org/IServiceEBanka/vratiStanjeResponse")]
        System.Threading.Tasks.Task<string> vratiStanjeAsync(string brRacuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEBanka/prebaciSaDeviznog", ReplyAction="http://tempuri.org/IServiceEBanka/prebaciSaDeviznogResponse")]
        void prebaciSaDeviznog(string racun, float kolicina, float EURDIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEBanka/prebaciSaDeviznog", ReplyAction="http://tempuri.org/IServiceEBanka/prebaciSaDeviznogResponse")]
        System.Threading.Tasks.Task prebaciSaDeviznogAsync(string racun, float kolicina, float EURDIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEBanka/prebaciSaDinarskog", ReplyAction="http://tempuri.org/IServiceEBanka/prebaciSaDinarskogResponse")]
        void prebaciSaDinarskog(string racun, float kolicina, float EURDIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEBanka/prebaciSaDinarskog", ReplyAction="http://tempuri.org/IServiceEBanka/prebaciSaDinarskogResponse")]
        System.Threading.Tasks.Task prebaciSaDinarskogAsync(string racun, float kolicina, float EURDIN);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEBanka/kreirajRacun", ReplyAction="http://tempuri.org/IServiceEBanka/kreirajRacunResponse")]
        void kreirajRacun(string brRacuna, float dinarski, float devizni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEBanka/kreirajRacun", ReplyAction="http://tempuri.org/IServiceEBanka/kreirajRacunResponse")]
        System.Threading.Tasks.Task kreirajRacunAsync(string brRacuna, float dinarski, float devizni);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEBanka/vratiIznosDinarski", ReplyAction="http://tempuri.org/IServiceEBanka/vratiIznosDinarskiResponse")]
        string vratiIznosDinarski(string brRacuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEBanka/vratiIznosDinarski", ReplyAction="http://tempuri.org/IServiceEBanka/vratiIznosDinarskiResponse")]
        System.Threading.Tasks.Task<string> vratiIznosDinarskiAsync(string brRacuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEBanka/vratiIznosDevizni", ReplyAction="http://tempuri.org/IServiceEBanka/vratiIznosDevizniResponse")]
        string vratiIznosDevizni(string brRacuna);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceEBanka/vratiIznosDevizni", ReplyAction="http://tempuri.org/IServiceEBanka/vratiIznosDevizniResponse")]
        System.Threading.Tasks.Task<string> vratiIznosDevizniAsync(string brRacuna);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceEBankaChannel : EBankaInterface.ServiceReference1.IServiceEBanka, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEBankaClient : System.ServiceModel.ClientBase<EBankaInterface.ServiceReference1.IServiceEBanka>, EBankaInterface.ServiceReference1.IServiceEBanka {
        
        public ServiceEBankaClient() {
        }
        
        public ServiceEBankaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEBankaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEBankaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEBankaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string vratiStanje(string brRacuna) {
            return base.Channel.vratiStanje(brRacuna);
        }
        
        public System.Threading.Tasks.Task<string> vratiStanjeAsync(string brRacuna) {
            return base.Channel.vratiStanjeAsync(brRacuna);
        }
        
        public void prebaciSaDeviznog(string racun, float kolicina, float EURDIN) {
            base.Channel.prebaciSaDeviznog(racun, kolicina, EURDIN);
        }
        
        public System.Threading.Tasks.Task prebaciSaDeviznogAsync(string racun, float kolicina, float EURDIN) {
            return base.Channel.prebaciSaDeviznogAsync(racun, kolicina, EURDIN);
        }
        
        public void prebaciSaDinarskog(string racun, float kolicina, float EURDIN) {
            base.Channel.prebaciSaDinarskog(racun, kolicina, EURDIN);
        }
        
        public System.Threading.Tasks.Task prebaciSaDinarskogAsync(string racun, float kolicina, float EURDIN) {
            return base.Channel.prebaciSaDinarskogAsync(racun, kolicina, EURDIN);
        }
        
        public void kreirajRacun(string brRacuna, float dinarski, float devizni) {
            base.Channel.kreirajRacun(brRacuna, dinarski, devizni);
        }
        
        public System.Threading.Tasks.Task kreirajRacunAsync(string brRacuna, float dinarski, float devizni) {
            return base.Channel.kreirajRacunAsync(brRacuna, dinarski, devizni);
        }
        
        public string vratiIznosDinarski(string brRacuna) {
            return base.Channel.vratiIznosDinarski(brRacuna);
        }
        
        public System.Threading.Tasks.Task<string> vratiIznosDinarskiAsync(string brRacuna) {
            return base.Channel.vratiIznosDinarskiAsync(brRacuna);
        }
        
        public string vratiIznosDevizni(string brRacuna) {
            return base.Channel.vratiIznosDevizni(brRacuna);
        }
        
        public System.Threading.Tasks.Task<string> vratiIznosDevizniAsync(string brRacuna) {
            return base.Channel.vratiIznosDevizniAsync(brRacuna);
        }
    }
}
