//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Materijal", Namespace="http://schemas.datacontract.org/2004/07/WCFjoks")]
    [System.SerializableAttribute()]
    public partial class Materijal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NazivField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float RoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private float VField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Naziv {
            get {
                return this.NazivField;
            }
            set {
                if ((object.ReferenceEquals(this.NazivField, value) != true)) {
                    this.NazivField = value;
                    this.RaisePropertyChanged("Naziv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float Ro {
            get {
                return this.RoField;
            }
            set {
                if ((this.RoField.Equals(value) != true)) {
                    this.RoField = value;
                    this.RaisePropertyChanged("Ro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float V {
            get {
                return this.VField;
            }
            set {
                if ((this.VField.Equals(value) != true)) {
                    this.VField = value;
                    this.RaisePropertyChanged("V");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.ICisterna")]
    public interface ICisterna {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/dodaj", ReplyAction="http://tempuri.org/ICisterna/dodajResponse")]
        void dodaj(WindowsFormsApp1.ServiceReference1.Materijal m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/dodaj", ReplyAction="http://tempuri.org/ICisterna/dodajResponse")]
        System.Threading.Tasks.Task dodajAsync(WindowsFormsApp1.ServiceReference1.Materijal m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/ispusti", ReplyAction="http://tempuri.org/ICisterna/ispustiResponse")]
        void ispusti(float v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/ispusti", ReplyAction="http://tempuri.org/ICisterna/ispustiResponse")]
        System.Threading.Tasks.Task ispustiAsync(float v);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/stanje", ReplyAction="http://tempuri.org/ICisterna/stanjeResponse")]
        WindowsFormsApp1.ServiceReference1.Materijal stanje();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/stanje", ReplyAction="http://tempuri.org/ICisterna/stanjeResponse")]
        System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Materijal> stanjeAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/svePromene", ReplyAction="http://tempuri.org/ICisterna/svePromeneResponse")]
        string[] svePromene();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICisterna/svePromene", ReplyAction="http://tempuri.org/ICisterna/svePromeneResponse")]
        System.Threading.Tasks.Task<string[]> svePromeneAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICisternaChannel : WindowsFormsApp1.ServiceReference1.ICisterna, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CisternaClient : System.ServiceModel.ClientBase<WindowsFormsApp1.ServiceReference1.ICisterna>, WindowsFormsApp1.ServiceReference1.ICisterna {
        
        public CisternaClient() {
        }
        
        public CisternaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CisternaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CisternaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CisternaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void dodaj(WindowsFormsApp1.ServiceReference1.Materijal m) {
            base.Channel.dodaj(m);
        }
        
        public System.Threading.Tasks.Task dodajAsync(WindowsFormsApp1.ServiceReference1.Materijal m) {
            return base.Channel.dodajAsync(m);
        }
        
        public void ispusti(float v) {
            base.Channel.ispusti(v);
        }
        
        public System.Threading.Tasks.Task ispustiAsync(float v) {
            return base.Channel.ispustiAsync(v);
        }
        
        public WindowsFormsApp1.ServiceReference1.Materijal stanje() {
            return base.Channel.stanje();
        }
        
        public System.Threading.Tasks.Task<WindowsFormsApp1.ServiceReference1.Materijal> stanjeAsync() {
            return base.Channel.stanjeAsync();
        }
        
        public string[] svePromene() {
            return base.Channel.svePromene();
        }
        
        public System.Threading.Tasks.Task<string[]> svePromeneAsync() {
            return base.Channel.svePromeneAsync();
        }
    }
}
